services:
  - type: web
    name: kisanpukar-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_NUMBER
        sync: false
      - key: AIRTABLE_TOKEN
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
